server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

console-available: true
spring:
  output:
    ansi:
      enabled: ALWAYS
