
spring:
  application:
    name: my-prometheus

server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}