server:
  port: 8180

#### Spring
spring:
  profiles:
    active: @project.env@

#### Eureka :
eureka:
  instance:
    prefer-ip-address: true # 将自己的 IP 注册到 Eureka Server 上面。
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

