
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.12:8761/eureka/

console-available: true

spring:
  profiles: test
  http:
    multipart:
    maxFileSize:  10Mb
    maxRequestSize: 100Mb
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # 原来是: 39.107.157.152:3306
    url: jdbc:mysql://192.168.1.6:3306/myspring?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: mima
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5 # 初始化大小
    minIdle: 5
    maxActive: 20
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false        # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


